# Generated by Django 6.0.6 on 2026-06-24 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('shopping', 'Пазаруване'), ('medicine', 'Доставка на лекарства'), ('transport', 'Транспорт'), ('company', 'Социална активност'), ('other', 'Друго')], max_length=30)),
                ('start_location', models.CharField(blank=True, max_length=200)),
                ('end_location', models.CharField(blank=True, max_length=200)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_note', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('open', 'Отворена'), ('assigned', 'Има одобрен кандидат'), ('closed', 'Затворена')], default='open', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Изчакваща'), ('accepted', 'Приета'), ('rejected', 'Отхвърлена')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('help_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='help_requests.helprequest')),
            ],
            options={
                'unique_together': {('help_request', 'applicant')},
            },
        ),
    ]
